### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by NyakoFox** [retronx-team/love-nx#11]
I was looking for an alternative to lovepotion, and I found this repository, and it works great.

I was wondering if this project is still alive, since there hasn't been a commit in a while. It would be nice for it to support Love2d 12 when that rolls around.

**Comment by NyakoFox** [comment]
Going to mention @HTV04 as you seem to be the active one

**Comment by p-sam** [comment]
Probably not active, but as long as it's still working that's good. I don't think I'll take the time to port 11.5 even if the changes are minor, but I may check out love2d 12 when it releases

**Comment by NyakoFox** [comment]
it'd be very much appreciated if you manage to get a love2d 12 port working on the switch!!
