### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by AM7999** [retronx-team/love-nx#8]
While not directly an issue with love-nx itself i am getting an issue with compiling love-nx. While running build.sh i am given the following error ![image](https://user-images.githubusercontent.com/62681612/159148383-a3a7c2d2-8f02-4494-ac4d-e835ebcec872.png)
And when looking in /opt/devkitpro/ for the sh its looking for no sh is there  ![image](https://user-images.githubusercontent.com/62681612/159148417-5cdd7930-5435-4e9f-bc19-b047e4f3f368.png)

**Comment by p-sam** [comment]
Yeah you're missing the package that script is from https://github.com/devkitPro/pacman-packages/blob/master/dkp-toolchain-vars/switchvars.sh

**Comment by AM7999** [comment]
Ah, alright

**Comment by AM7999** [comment]
So just now i have tried to run build.sh and i'm assuming this is an error with compiling love 
![image](https://user-images.githubusercontent.com/62681612/159172529-45fb4096-6239-4a8d-b28d-9d56c233341f.png)

And if this helps here's the log
[CMakeOutput.log](https://github.com/retronx-team/love-nx/files/8311660/CMakeOutput.log)

**Comment by p-sam** [comment]
@AM7999 Check if your issue still persists with the latest commit on develop. Your error is weird though and my fix is probably unrelated so you should probably double check your setup

**Comment by AM7999** [comment]
It _might_ be with me compiling an older version of love for the switch (for games that need an older version of love)

**Comment by p-sam** [comment]
ah yeah most definitely, as the source includes the patches. I will close the issue then
